/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Cubie(props) {
  const { nodes, materials } = useGLTF("/cubie.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame.geometry}
        material={materials.BLACK}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Red.geometry}
        material={materials.RED}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Blue.geometry}
        material={materials.BLUE}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Yellow.geometry}
        material={materials.YELLOW}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.White.geometry}
        material={materials.WHITE}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Green.geometry}
        material={materials.GREEN}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pink.geometry}
        material={materials.PINK}
      />
    </group>
  );
}

useGLTF.preload("/cubie.glb");